### ISSUE TITLE
Error response from daemon

### ISSUE THREAD

**Issue by XScorpion2** [randellhodges/compose-sentry#1]
"2018-10-29 04:00:00 INFO     Error response from daemon: no such image: Error: No such object:: invalid reference format: repository name must be lowercase updated"
Any idea what this error means?

**Comment by randellhodges** [comment]
Error handling in this leaves a lot to be desired.  Do a docker ps -a and a docker images and see if you have anything around that shouldn't be. Clean up any leftovers and then see what happens.

Are your images from dockerhub, or a different repo? I have only tested with dockerhub images.

**Comment by XScorpion2** [comment]
I have 1 image that is still around that is not completely required. It's a dependent for a custom created image. The compose files I've given sentry though do not point to any container using that image, or the custom image. All images (except the custom one) are from hub.docker.com. Configuration below:

`  compose-sentry:
    container_name: compose-sentry
    restart: always
    image: randellhodges/compose-sentry:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME_DIR}/sentry:/config
      - ${HOME_DIR}/docker-compose.yml:/config/portainer.yml:ro
      - ${HOME_DIR}/portainer/data/compose/5/docker-compose.yml:/config/watcher.yml:ro
      - ${HOME_DIR}/portainer/data/compose/10/docker-compose.yml:/config/networkservices.yml:ro
      - ${HOME_DIR}/portainer/data/compose/11/docker-compose.yml:/config/homeautomation.yml:ro
      - ${HOME_DIR}/portainer/data/compose/15/docker-compose.yml:/config/openvpn.yml:ro`

`scheduler:
  max_threads: 20
  max_processes: 10
  misfire_grace_time: 30
logger:
  default: error
  log_file: /config/sentry.log
  logs:
    composesentry: info
    apscheduler: warn
hosts:
  local:
    host: unix:///var/run/docker.sock
jobs:
  - id: Job 1
    file: /config/portainer.yml
    host: local
    schedule: '0 4 * * *'
    cleanup: true
  - id: Job 2
    file: /config/networkservices.yml
    host: local
    schedule: '0 4 * * *'
    cleanup: true
  - id: Job 3
    file: /config/homeautomation.yml
    host: local
    schedule: '0 4 * * *'
    cleanup: true
  - id: Job 4
    file: /config/openvpn.yml
    host: local
    schedule: '0 4 * * *'
    cleanup: true
  - id: Job 5
    file: /config/watcher.yml
    host: local
    schedule: '0 4 * * *'
    cleanup: true`

**Comment by randellhodges** [comment]
Are you able to determine which particular job it is failing? Try setting the log level on composesentry to debug. You should then see be able to see the full commands being executed. We can then narrow down which one is having problems.

I recommend finding the 1 job that has the issue and the commenting out the others and then enabling debug. It can get a little chatty.

**Comment by XScorpion2** [comment]
I tried to nail it down to a specific job and it turns out it's all jobs. Using the debug log level, I saw the commands it was running:
docker-compose -f /config/portainer.yml ps -q
docker inspect --format {{.Image}}
...and more

The second command looked like it failed injecting an image name, so I ran the first command on the container, and turns out the first command is the problem. It is not listing any containers for that docker-compose file using the compose-sentry shell, using the host it does. Going even further, only 1 of those 5 compose files return images on the host, none in compose-sentry shell.

**Comment by XScorpion2** [comment]
there's a verbose option for docker-compose and using that I was able to figure out why it is failing. Still working on getting it running, my docker volume mounts are screwed up atm.

The root of the problem is that docker-compose ps looks for the network (stack) by using the directory the compose file is located in as the stack name. So /config/portainer.yml was looking for images in the config_default network, when in fact it should be looking in docker_default for that one. I'm updating my volume mounts to have the correct directory structure and seeing if that fixes the issue.
/config/portainer.yml -> /config/docker/docker_compose.yml

**Comment by XScorpion2** [comment]
Hey, so something for you to check on your end is the volume mounting in your latest image. The first time I did my config mounts was before your image push 3 days ago, and the compose files mounted and appeared in the config folder just fine. But today when trying to rework those mounts, they are now failing to mount properly, and just displaying as empty files.

**Comment by randellhodges** [comment]
Will do

**Comment by XScorpion2** [comment]
nm on the volume mount, after a host reboot it's mounting the files correctly now, and ps command works just fine with the files now being under directories named the same as the stack name:
docker-compose -f /config/docker/docker-compose.yml ps -q
7479a0ad95f1fc1f79edf059e42948b37da641e79d378826027e4f51096c9db6

So with any luck, it will run tonight and update cleanly.

**Comment by XScorpion2** [comment]
And we have success! Thanks for walking me through this trouble shooting.

**Comment by randellhodges** [comment]
No problem. I'll try to get around to updating the wiki with
troubleshooting information.

What step do you think actually fixed your issue? Something that I could
more plainly explain in the readme?  I know I'm not the best at
documentation.
